# This file configures TEM and MADS parameters for STEP4 of the calibration 
# EJ 03/02/23
calib_mode: VEGC
# Calibration cases from the calibration/calibration_targets.py
# The output will be selected based on this cases
target_names: 
#- GPPAllIgnoringNitrogen
#- NPPAllIgnoringNitrogen
#- NPPAll
- VegCarbon
#- VegStructuralNitrogen
#- MossDeathC
#- CarbonShallow
#- CarbonDeep
#- CarbonMineralSum
#- OrganicNitrogenSum
#- AvailableNitrogenSum
cmtnum: 1
opt_run_setup: --pr-yrs 100 --eq-yrs 200 --sp-yrs 0 --tr-yrs 0 --sc-yrs 0
params:
#- nmax 
#- nmax
#- nmax
#- nmax
#- krb(0)
#- krb(0)
#- krb(0)
#- krb(0)
#- krb(1)
#- krb(1)
#- krb(1)
#- krb(2)
#- krb(2)
#- krb(2)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(0)
- cfall(1)
- cfall(1)
- cfall(1)
- cfall(2)
- cfall(2)
- cfall(2)
#- nfall(0)
#- nfall(0)
#- nfall(0)
#- nfall(0)
#- nfall(1)
#- nfall(1)
#- nfall(1)
#- nfall(2)
#- nfall(2)
#- nfall(2)
#- micbnup 
#- kdcrawc 
#- kdcsoma 
#- kdcsompr
#- kdcsomcr
pftnums:
#- 0
#- 1
#- 2
#- 3
- 0
- 1
- 2
- 3
- 0
- 1
- 2
- 0
- 1
- 2
#- 0
#- 1
#- 2
#- 3
#- 0
#- 1
#- 2
#- 0
#- 1
#- 2
#- 0
#- 1
#- 2
#- 3
#- 0
#- 1
#- 2
#- 0
#- 1
#- 2
#- None
#- None
#- None
#- None
#- None
site: /data/input-catalog/cru-ts40_ar5_rcp85_mri-cgcm3_MurphyDome_10x10
work_dir: /data/workflows/cfall-vegc-md1
mads_initial_guess:
- 0.001902	
- 0.069358	
- 0.052843	
- 0.016696	
- 0.003470	
- 0.003065	
- 0.004257	
- 0.006388	
- 0.002882	
- 0.019844	
# NOTE: Kdcraw > Kdcactive > Kdcpr > Kdccr
mads_paramdist:
- Uniform(0.000814, 0.002897)
- Uniform(0.02073, 0.112996)
- Uniform(0.024987, 0.085420)
- Uniform(0.007194, 0.023174)
- Uniform(0.003176, 0.004183)
- Uniform(0.000994, 0.005518)
- Uniform(0.002478, 0.006488)
- Uniform(0.005036, 0.007781)
- Uniform(0.001171, 0.004697)
- Uniform(0.008196, 0.031280)
mads_paramkey:
- cfall00
- cfall01
- cfall02
- cfall03
- cfall10
- cfall11
- cfall12
- cfall20
- cfall21
- cfall22
# mads_obsrange (ON, OFF) sets ranges for observations
mads_obsrange: 'OFF'
mads_obs_percent_variance: 1
# mads_paramrange (ON, OFF) sets ranges for parameters
mads_paramrange: 'OFF'
mads_param_percent_variance: 70
mads_problemname: cfall-vegc-MD1-EJ
